apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: pushsecret # Customisable
  namespace: {{ .Values.dsp.name }} # Same of the SecretStores
spec:
  updatePolicy: Replace # Policy to overwrite existing secrets in the provider on sync
  deletionPolicy: Delete # the provider' secret will be deleted if the PushSecret is deleted
  refreshInterval: 10s # Refresh interval for which push secret will reconcile
  secretStoreRefs: # A list of secret stores to push secrets to
    - name: {{ .Values.secretStore.name }}
      kind: {{ .Values.secretStore.kind }}
  selector:
    secret:
      name: {{ .Values.dsp.name }}-obc # Source Kubernetes secret to be pushed
  data:
    - conversionStrategy: None # Also supports the ReverseUnicode strategy
      match:
        secretKey: AWS_ACCESS_KEY_ID # Source Kubernetes secret key to be pushed
        remoteRef:
          remoteKey: "secret/data/global/{{ .Values.dsp.name }}-aws-access-key" # Remote reference (where the secret is going to be pushed)
      - conversionStrategy: None # Also supports the ReverseUnicode strategy
      match:
        secretKey: AWS_SECRET_ACCESS_KEY # Source Kubernetes secret key to be pushed
        remoteRef:
          remoteKey: "secret/data/global/{{ .Values.dsp.name }}-aws-secret-access-key" # Remote reference (where the secret is going to be pushed